services:
  - type: web
    name: timeoff-management
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: timeoff-db
          property: connectionString

databases:
  - name: timeoff-db
    databaseName: timeoff
    ipAllowList: []
    plan: free